---
- hosts: appserver
  remote_user: root
  become: true
  gather_facts: false
  tasks:
  - name: download package from artifactory server
    command: wget http://35.196.201.46:8081/artifactory/abcbank-package/petclinic.war
  - name: deploy war file to server
    command: cp ~/petclinic.war /opt/apache-tomcat-8.5.30/webapps/
  - name: restart app server
    command: sleep 20; sh /opt/apache-tomcat-8.5.30/bin/catalina.sh start
